### ISSUE TITLE
wf

### ISSUE THREAD

**Issue by nghiabtc** [Widiskel/evm-tx-deployer-bot#2]
i used your code. and recently i found out that i lost my linked wallet assets, which never happened before. when i checked the codes again i found out that only your code was encrypted and could not be decrypted. this means that your bad code might have stolen my linked wallet assets.
if so then you are trash..

**Comment by copycatcodex** [comment]
check again how many codes you have used for your asset wallet so that it is lost / wallet drain.

**Comment by Widiskel** [comment]
this code is not encrypted
